name: build-base

on:
  push:
    branches:
      - master
    paths:
      - 'docker/arch/**'
      - '.forgejo/workflows/build-base.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    container:
      image: git.sylvainleclercq.com/depassage/ci-node-docker:22-bookworm

    steps:
      - uses: actions/checkout@v4

      - name: Show docker
        run: docker version

      - name: Login to Forgejo registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login git.sylvainleclercq.com -u depassage --password-stdin

      - name: Build image
        run: docker build -t git.sylvainleclercq.com/depassage/coder-base:${{ github.sha }} -f docker/arch/Dockerfile docker/arch

      - name: Push sha tag
        run: docker push git.sylvainleclercq.com/depassage/coder-base:${{ github.sha }}

      - name: Tag nightly
        run: docker tag git.sylvainleclercq.com/depassage/coder-base:${{ github.sha }} git.sylvainleclercq.com/depassage/coder-base:nightly

      - name: Push nightly
        run: docker push git.sylvainleclercq.com/depassage/coder-base:nightly
